# Generated by Django 5.0.7 on 2024-07-30 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_post_image_alter_profile_profile_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newslettersubscription',
            name='subscribed_to',
        ),
        migrations.RemoveField(
            model_name='newslettersubscription',
            name='user',
        ),
        migrations.DeleteModel(
            name='Newsletter',
        ),
        migrations.DeleteModel(
            name='NewsletterSubscription',
        ),
    ]
