# Generated by Django 5.0.7 on 2024-08-01 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_post_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='read',
        ),
    ]
